spring:

  application:
    ui:
      title: Terran Republic Interstellar Plotter (TRIPS)

  # spring datasource requirements
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolZZZ
    url: jdbc:h2:file:./data/tripsdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # spring data jpa settings
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # spring default security
  security:
    user:
      name: Caine
      password: Mutiny

  # Enabling H2 Console
  h2:
    console:
      enabled: true

      # Custom H2 Console URL
      path: /h2
app:
  title: Terran Republic Interstellar Plotting System (TRIPS)
  version: v0.5.2
  releaseDate: 31 Aug 2020
  contributors: LJ Ramones, CE Gannon, R Boatright
  projectPage: https://github.com/ljramones/trips
  fileDirectory: files