spring:

  application:
    ui:
      title: Terran Republic Interstellar Plotter (TRIPS)

  # spring datasource requirements
  datasource:
    hikari:
      minimum-idle: 0
      initialization-fail-timeout: -1
      connectionTimeout: 20000
      maximumPoolSize: 5
      poolName: HikariPoolTrips
    url: jdbc:h2:file:./data/tripsdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    continue-on-error: true

  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  # spring default security
  security:
    user:
      name: Caine
      password: Mutiny

  # Enabling H2 Console
  h2:
    console:
      enabled: true

      # Custom H2 Console URL
      path: /h2
app:
  title: Terran Republic Interstellar Plotting System (TRIPS)
  version: v0.6.3
  releaseDate: 7 Feb 2021
  contributors: LJ Ramones, CE Gannon, R Boatright
  projectPage: https://github.com/ljramones/trips
  fileDirectory: files